### ISSUE TITLE
Missing modules in pygmo

### ISSUE THREAD

**Issue by alexshade15** [esa/pagmo2#321]
Hello,
I'm working on windows 10, python 2.7 and i've installed pygmo with pip.

The problme in that if i try to import some modules like gaco or gwo from pygmo I get the following message:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name gaco
```

It seems that the problem is that in my pygmo there are some missing modules

```
pygmo = {module} <module 'pygmo' from 'C:\Python27\lib\site-packages\pygmo\__init__.pyc'>
 _ai = {_Feature} _Feature((2, 5, 0, 'alpha', 1), (3, 0, 0, 'alpha', 0), 16384)
 _atexit = {module} <module 'atexit' from 'C:\Python27\lib\atexit.pyc'>
 _cloudpickle = {module} <module 'cloudpickle' from 'C:\Python27\lib\site-packages\cloudpickle\__init__.pyc'>
 _patch_algorithm = {module} <module 'pygmo._patch_algorithm' from 'C:\Python27\lib\site-packages\pygmo\_patch_algorithm.pyc'>
 _patch_island = {module} <module 'pygmo._patch_island' from 'C:\Python27\lib\site-packages\pygmo\_patch_island.pyc'>
 _patch_problem = {module} <module 'pygmo._patch_problem' from 'C:\Python27\lib\site-packages\pygmo\_patch_problem.pyc'>
 _serialization_backend = {module} <module 'cloudpickle' from 'C:\Python27\lib\site-packages\cloudpickle\__init__.pyc'>
 _version = {module} <module 'pygmo._version' from 'C:\Python27\lib\site-packages\pygmo\_version.pyc'>
 ackley = {class} <class 'pygmo.core.ackley'>
 algorithm = {class} <class 'pygmo.core.algorithm'>
 algorithms = {module} <module 'pygmo.core.algorithms' (built-in)>
 archipelago = {class} <class 'pygmo.core.archipelago'>
 bee_colony = {class} <class 'pygmo.core.bee_colony'>
 bf_approx = {class} <class 'pygmo.core.bf_approx'>
 bf_fpras = {class} <class 'pygmo.core.bf_fpras'>
 cec2006 = {class} <class 'pygmo.core.cec2006'>
 cec2009 = {class} <class 'pygmo.core.cec2009'>
 cec2013 = {class} <class 'pygmo.core.cec2013'>
 cec2014 = {class} <class 'pygmo.core.cec2014'>
 cmaes = {class} <class 'pygmo.core.cmaes'>
 compass_search = {class} <class 'pygmo.core.compass_search'>
 core = {module} <module 'pygmo.core' from 'C:\Python27\lib\site-packages\pygmo\core.pyd'>
 cstrs_self_adaptive = {class} <class 'pygmo.core.cstrs_self_adaptive'>
 de = {class} <class 'pygmo.core.de'>
 de1220 = {class} <class 'pygmo.core.de1220'>
 decompose = {class} <class 'pygmo.core.decompose'>
 decorator_problem = {type} <class 'pygmo._py_problems.decorator_problem'>
 dtlz = {class} <class 'pygmo.core.dtlz'>
 evolve_status = {type} <class 'pygmo.evolve_status'>
 griewank = {class} <class 'pygmo.core.griewank'>
 hock_schittkowsky_71 = {class} <class 'pygmo.core.hock_schittkowsky_71'>
 hv2d = {class} <class 'pygmo.core.hv2d'>
 hv3d = {class} <class 'pygmo.core.hv3d'>
 hvwfg = {class} <class 'pygmo.core.hvwfg'>
 hypervolume = {class} <class 'pygmo.core.hypervolume'>
 ihs = {class} <class 'pygmo.core.ihs'>
 inventory = {class} <class 'pygmo.core.inventory'>
 ipyparallel_island = {type} <class 'pygmo._py_islands.ipyparallel_island'>
 island = {class} <class 'pygmo.core.island'>
 islands = {module} <module 'pygmo.core.islands' (built-in)>
 luksan_vlcek1 = {class} <class 'pygmo.core.luksan_vlcek1'>
 mbh = {class} <class 'pygmo.core.mbh'>
 minlp_rastrigin = {class} <class 'pygmo.core.minlp_rastrigin'>
 moead = {class} <class 'pygmo.core.moead'>
 mp_island = {type} <class 'pygmo._py_islands.mp_island'>
 nlopt = {class} <class 'pygmo.core.nlopt'>
 nsga2 = {class} <class 'pygmo.core.nsga2'>
 null_algorithm = {class} <class 'pygmo.core.null_algorithm'>
 null_problem = {class} <class 'pygmo.core.null_problem'>
 plotting = {module} <module 'pygmo.plotting' from 'C:\Python27\lib\site-packages\pygmo\plotting\__init__.pyc'>
 population = {class} <class 'pygmo.core.population'>
 problem = {class} <class 'pygmo.core.problem'>
 problems = {module} <module 'pygmo.core.problems' (built-in)>
 pso = {class} <class 'pygmo.core.pso'>
 pso_gen = {class} <class 'pygmo.core.pso_gen'>
 rastrigin = {class} <class 'pygmo.core.rastrigin'>
 rosenbrock = {class} <class 'pygmo.core.rosenbrock'>
 sade = {class} <class 'pygmo.core.sade'>
 schwefel = {class} <class 'pygmo.core.schwefel'>
 sea = {class} <class 'pygmo.core.sea'>
 sga = {class} <class 'pygmo.core.sga'>
 simulated_annealing = {class} <class 'pygmo.core.simulated_annealing'>
 test = {module} <module 'pygmo.test' from 'C:\Python27\lib\site-packages\pygmo\test.pyc'>
 thread_island = {class} <class 'pygmo.core.thread_island'>
 thread_safety = {type} <class 'pygmo.thread_safety'>
 translate = {class} <class 'pygmo.core.translate'>
 unconstrain = {class} <class 'pygmo.core.unconstrain'>
 xnes = {class} <class 'pygmo.core.xnes'>
 zdt = {class} <class 'pygmo.core.zdt'>
```

I also tried to reinstall pygmo, but nothing seem to change.

**Comment by bluescarni** [comment]
@alexshade15 ``gwo`` and ``aco`` are part of the next pagmo release, 2.11. We plan to do the release later next week, after that you'll be able to use these new algorithms (after updating pagmo).
